# Generated by Django 4.2.5 on 2023-09-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
        ("tasks", "0003_alter_task_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_name",
                to="statuses.status",
            ),
        ),
    ]
