# Generated by Django 4.2.5 on 2023-09-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
        ("labels", "0001_initial"),
        ("tasks", "0004_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statuses",
                to="statuses.status",
            ),
        ),
        migrations.CreateModel(
            name="LabelDeleteProtection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="labels.label"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tasks.task"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="label",
            field=models.ManyToManyField(
                blank=(True,),
                related_name="labels",
                through="tasks.LabelDeleteProtection",
                to="labels.label",
            ),
        ),
    ]
