# Generated by Django 4.2.5 on 2023-09-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0005_alter_task_status_labeldeleteprotection_task_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="label",
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=(True,),
                related_name="labels",
                through="tasks.LabelDeleteProtection",
                to="labels.label",
            ),
        ),
    ]
