# Generated by Django 4.2.5 on 2023-10-04 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("statuses", "0001_initial"),
        ("tasks", "0006_remove_task_label_task_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labeldeleteprotection",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executor",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=(True,),
                related_name="labels",
                through="tasks.LabelDeleteProtection",
                to="labels.label",
                verbose_name="Labels",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statuses",
                to="statuses.status",
                verbose_name="Status",
            ),
        ),
    ]
